language: node_js
node_js:
  - 6
env:
  matrix:
    secure: jOnmEgpPWIOeOu+O3jmoJL0nQfhQFdG+gnn/4NEnhTZ33A5M4FEUeKuwfHjr+lL92BsVYopA//E+YMRDCHGvymNIH2W0Uv79xVryMd4H6SsMyA1SavHUIpdyAXrP7HHY8hXHSyvbZjwvkCy1Xtz19qomf3lwu65Oss3Q6TYVQV7HFUm6N7s2i65kZ2wVyk9qyxs304+6GTKmhIb2/cICe67L2eV3jw2ztIZAKyfuGQuHUYQx6uK70tTd+9U74Sx3+GCbfHtvQrPYB04dk3ELApOlOlnkMXndKKRNYsb35i4D0ovH81U7ebMmh6xPcwfq1umQ+OznYMwX1nanq1SN6HLDBbLj7jYK2chIXTAftKnyErE+07bsKBnRFVMLCBwOA3sjq08cdXiTvIG5XJQmOrxta5ft81uvFtBN2N6DD5izSMhQElLmLhLR/yp3BJB3/7tvmhevUi8xy78d3B6jN/6UhDoPkVMBGqMXyblGo3Hks+SLwDc3nthX22hNbliDCe5wkyo2GY2veb7oz/kpUOsdGncrYMFR/uXdyp3Xz9TLvD6vOit1n0rSI168rHvu+sepdMe6q6ZYXSr7VzKYjJEYQYYInQPRDv08Fv5rQYn5WbwhtsoPp+0whXlxg6nO5ATLWpeW+cEqI6FoGd00jC1eEt248POrX7SYBEKBw4s=
